<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'avatar' => '头像',
    'Admins' => '管理员列表',
    'Apps' => '应用列表',
    'company' => '公司',
    'Cancel' => '取消',
    'Create' => '创建',
    'Create Admin' => '创建管理员',
    'create time' => '创建时间',
    'Create App' => '创建应用',
    'description' => '描述',
    'email' => '邮箱',
    'id' => 'ID',
    'Message' => '推送消息',
    'phone' => '手机',
    'status' => '状态',
    'update time' => '更新时间',
    'user id' => '用户ID',
    'username' => '用户名',
    'password' => '密码',
    'copyright' => '2016 &copy; 蘑菇云',
    'Update' => '更新',
    'Update {modelClass}' => '更新 {modelClass}',
    'Delete' => '删除',
    'Submit' => '提交',
    'Reset' => '重置',
    'Incorrect username or password' => '账号或密码错误',
    'Signup' => '注册',
    'Already have a account' => '已有账号',
    'Back' => '返回',
    'Don\'t have an account yet' => '还没有账号',
    'Forgot your password' => '忘记密码',
    'Login' => '登录',
    'Login now' => '立录登录',
    'Login to your account' => '登录账号',
    'Remember me' => '记录密码',
    'Sign Up' => '注册',
    'no worries, click {tag} here {tagEnd} to reset your password' => '点击{tag}这里{tagEnd}找回密码',
    'Create an account' => '注册账号',
    'Enter your personal details below' => '请输入个人信息',
    'Enter your account details below' => '请输入账号信息',

    //change-password
    'old password' => '原密码',
    'password must contains at least one digit' => '密码至少包含一位数字',
    'password must contains at least one letter' => '密码至少包含一个字母',
    'the new password can not be the same as the original password' => '新密码不能和原密码相同',
    'user does not exist' => '用户不存在',
    'the original password is incorrect' => '原密码不正确',
    //reset-password
    'sms code' => '短信验证码',
    'error sms code' => '短信验证码错误',
    //sms-code
    'phone number is required' => '手机号必须',
    'invalid phone number format' => '手机号码格式不正确',
    'Your sms code is {code}. Do not tell others. Ignore if you never sent it!' =>
        '您的验证码是：{code}。请不要把验证码泄露给其他人。如非本人操作，可不用理会！',
    'Failed to sent the sms code' => '验证码发送失败',
];