<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'avatar' => '头像',
    'Admins' => '管理员列表',
    'Apps' => '应用列表',
    'App Device' => '应用设备',
    'App Device Tag' => '设备标签',
    'App Tag' => '应用标签',
    'App Push Logs' => '应用推送日志',
    'app description' => '应用描述',
    'app key' => 'App Key',
    'app name' => '应用名称',
    'app icon' => '应用图标',
    'app secret' => 'App Secret',
    'company' => '公司',
    'Cancel' => '取消',
    'Create' => '创建',
    'Create Admin' => '创建管理员',
    'create time' => '创建时间',
    'Create App' => '创建应用',
    'description' => '描述',
    'email' => '邮箱',
    'id' => 'ID',
    'Message' => '推送消息',
    'phone' => '手机',
    'status' => '状态',
    'update time' => '更新时间',
    'user id' => '用户ID',
    'username' => '用户名',
    'password' => '密码',
    'copyright' => '2016 &copy; 蘑菇云',
    'Update' => '更新',
    'Update {modelClass}' => '更新 {modelClass}',
    'Delete' => '删除',
    'Submit' => '提交',
    'Reset' => '重置',
    'Incorrect username or password' => '账号或密码错误',
    'Signup'=>'注册'
];
