<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'avatar' => '頭像',
    'Admins' => '管理員列表',
    'Apps' => '應用列表',
    'company' => '公司',
    'Cancel' => '取消',
    'Create' => '創建',
    'Create Admin' => '創建管理員',
    'create time' => '創建時間',
    'Create App' => '創建應用',
    'description' => '描述',
    'email' => '郵箱',
    'id' => 'ID',
    'Message' => '推送消息',
    'phone' => '手機',
    'status' => '狀態',
    'update time' => '更新時間',
    'user id' => '用戶ID',
    'username' => '用戶名',
    'password' => '密碼',
    'copyright' => '2016 &copy; 蘑菇雲',
    'Update' => '更新',
    'Update {modelClass}' => '更新 {modelClass}',
    'Delete' => '刪除',
    'Submit' => '提交',
    'Reset' => '重置',
    'Incorrect username or password' => '賬號或密碼錯誤',
    'Signup'=>'註冊',
    'Already have a account' => '已有賬號',
    'Back' => '返回',
    'Don\'t have an account yet' => '還沒有賬號',
    'Forgot your password' => '忘記密碼',
    'Login' => '登錄',
    'Login now' => '立錄登錄',
    'Login to your account' => '登錄賬號',
    'Remember me' => '記錄密碼',
    'Sign Up' => '註冊',
    'no worries, click {tag} here {tagEnd} to reset your password' => '點擊{tag}這裡{tagEnd}找回密碼',
    'Create an account' => '註冊賬號',
    'Enter your personal details below' => '請輸入個人信息',
    'Enter your account details below' => '請輸入賬號信息',

     //change-password
    'old password' => '原密碼',
    'password must contains at least one digit' => '密碼至少包含一位數字',
    'password must contains at least one letter' => '密碼至少包含一個字母',
    'the new password can not be the same as the original password' => '新密碼不能和原密碼相同',
    'user does not exist' => '用戶不存在',
    'the original password is incorrect' => '原密碼不正確',
    //reset-password
    'sms code' => '短信驗證碼',
    'error sms code' => '短信驗證碼錯誤',
    //sms-code
    'phone number is required' => '手機號必須',
    'invalid phone number format' => '手機號碼格式不正確',
    'Your sms code is {code}. Do not tell others. Ignore if you never sent it!' =>
        '您的驗證碼是：{code}。請不要把驗證碼洩露給其他人。如非本人操作，可不用理會！ ',
     'Failed to sent the sms code' => '驗證碼發送失敗',
];
